[package]
name = "hubble"
version = "0.1.0"
edition = "2021"

[dependencies]
dysonsphere = { path = "../dysonsphere" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "process"] }
serde_json = "1"
log = "0.4"
env_logger = "0.11"
dotenvy = "0.15"
ureq = { version = "2", default-features = false, features = ["json", "tls"] }
